---
title: "Plotting sample sites: Metema and Metekel"
output: 
  github_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd(getwd())
```

## Load required packages

```{r, message=FALSE, warning=FALSE}
library(sf)
library(raster)
library(ggplot2)
library(ggspatial)
library(ggrepel)
library(dplyr)
```

## Get data

```{r}
load("../data/metema_output_GIS.RData")
eth_st <- getData(name = "GADM", country = "ETH", level = 2)  # level 2 for migration map
eth <- eth_st %>% st_as_sf()
```

## Create topographical map with rivers

```{r}
river_line_eth <- st_read("../data/DIVA_gis/ETH_wat/ETH_water_lines_dcw.shp") %>% st_as_sf()
bbox_buffer_wgs84 <- bbox_buffer_sf %>% st_transform(crs = "+init=epsg:4326")
river_line_eth_crop_wgs84 <- st_intersection(river_line_eth, bbox_buffer_wgs84)
water_areas <- water_areas %>% st_transform(crs = "+init=epsg:4326")
```

```{r}
populations_wgs84 <- populations_utm %>% st_as_sf() %>% st_transform(crs = "+init=epsg:4326")
bbox_eth_wgs84 <- bbox_eth_sp %>% st_as_sf() %>% st_transform(crs = "+init=epsg:4326")
```

## Calculate hillshade

```{r}
alt_r <- getData('alt', country='ETH')
alt <- trim(mask(alt_r, bbox_eth_wgs84))
slope <- raster::terrain(alt, opt='slope')
aspect <- terrain(alt, opt='aspect')

hill <- hillShade(slope, aspect, 40, 270)
```

## Plotting using ggplot 2

### Preparing data
```{r}
hs <-  hill
dem <- alt
#   Convert rasters TO dataframes for plotting with ggplot
hdf <- rasterToPoints(hs); hdf <- data.frame(hdf)
colnames(hdf) <- c("X","Y","Hill")
ddf <- rasterToPoints(dem); ddf <- data.frame(ddf)
colnames(ddf) <- c("X","Y","DEM")

#   Create vectors for colour breaks
b.hs <- seq(min(hdf$Hill),max(hdf$Hill),length.out=100)
b.dem <- seq(min(ddf$DEM),max(ddf$DEM),length.out=100)

populations_wgs84$sample_size <- c(31, 31, 12, 26, 29, 5) ## adding sample size information
populations_df <- data.frame(populations_wgs84)
populations_df <- cbind(populations_df, st_coordinates(populations_wgs84))
bbox_eth_district <- st_intersection(bbox_buffer_wgs84, eth)
```

### Plotting
```{r}
p <- ggplot() + 
  geom_raster(data = ddf, aes(X, Y, fill = DEM, alpha = 2)) +
  geom_raster(data = hdf, aes(X, Y, alpha = Hill)) +
  scale_fill_gradientn(name="Altitude (m)",colours = terrain.colors(20))+
  guides(fill = guide_colorbar()) +
  scale_alpha(range = c(0, 0.5), guide = "none") +
  coord_equal() + theme_void()


## Boundary
p1 <- p + 
  # geom_sf(data = bbox_eth_wgs84, col = "black", lwd = 1, lty = 1, alpha = 0.01) +
  geom_sf(data = river_line_eth_crop_wgs84, col = "steelblue", lwd = 0.8) +
  geom_sf(data = water_areas, fill = "lightblue", col = "black", alpha = .9) +
  geom_sf(data = bbox_eth_district, col = "black", lwd = .85, lty = 1, alpha = 0.01)

scale_bar <- p1 +
annotation_scale(location = "br", width_hint = 0.5, style = 'ticks')

direction <- scale_bar +
  annotation_north_arrow(location = "tl", which_north = "true",
        pad_x = unit(0.05, "in"), pad_y = unit(0.25, "in"),
        style = north_arrow_fancy_orienteering)


p3 <- direction + geom_point(data = populations_df, aes(X, Y, size = sample_size),shape = 21,  fill = "white", alpha = .9, colour = "black", stroke = 1.25) +
  geom_label_repel(data = populations_df, aes(X, Y, label = location), size = 4, alpha = 1) + theme_void(base_size = 14)

p3$labels$size <- "Samples" 

p3
```

## Save the plot
    
```{r}
ggsave(plot = p3, filename = "../figs/221213_sample_locations_vec_par.png", device = "png", dpi = 500, width = 5.5, height = 6, units = "in", bg = 'white')
```

## Session info

```{r}
sessionInfo()
```
